# Generated by Django 3.2.16 on 2025-05-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250508_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы,цифры, дефис и подчеркивание.', unique=True, verbose_name='Идентификатор'),
        ),
    ]
